name: feedstocks

on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch: null

jobs:
  feedstocks:
    name: feedstocks
    runs-on: "ubuntu-latest"
    steps:
      - name: skip me
        shell: bash -l {0}
        if: success() && contains(github.event.head_commit.message, 'ci skip')
        run: |
          echo "commit message: '${MSG}'"
          echo "CI_SKIP=true" >> $GITHUB_ENV
        env:
          MSG: ${{ github.event.head_commit.message }}

      - uses: actions/checkout@v2
        if: success() && ! env.CI_SKIP

      - name: turnstyle-python
        id: turnstyle
        uses: beckermr/turnstyle-python@v1
        if: success() && ! env.CI_SKIP
        with:
          continue-after-seconds: 10
          poll-interval-seconds: 5
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v2
        if: success() && ! env.CI_SKIP && ! steps.turnstyle.outputs.force_continued

      - uses: conda-incubator/setup-miniconda@v2
        if: success() && ! env.CI_SKIP && ! steps.turnstyle.outputs.force_continued
        with:
          python-version: 3.7
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true

      - name: do local setup and stop me if needed
        shell: bash -l {0}
        if: success() && ! env.CI_SKIP && ! steps.turnstyle.outputs.force_continued
        run: |
          source local_setup.sh
          # python stop_me_if_needed.py

      - name: install bot code
        shell: bash -l {0}
        if: success() && ! env.CI_SKIP && ! steps.turnstyle.outputs.force_continued
        run: |
          source install_bot_code.sh
        env:
          PASSWORD: ${{ secrets.AUTOTICK_BOT_TOKEN }}

      - name: feedstocks
        shell: bash -l {0}
        if: success() && ! env.CI_SKIP && ! steps.turnstyle.outputs.force_continued
        run: |
          pushd cf-graph
          conda activate run_env

          conda-forge-tick --run 0
          popd
        env:
          PASSWORD: ${{ secrets.AUTOTICK_BOT_TOKEN }}

      - name: deploy
        shell: bash -l {0}
        if: github.ref == 'refs/heads/master' && ! cancelled() && ! env.CI_SKIP && ! steps.turnstyle.outputs.force_continued
        run: |
          pushd cf-graph
          conda activate run_env

          export CIRCLE_BUILD_URL="https://github.com/regro/autotick-bot/actions/runs/${RUN_ID}"
          export CIRCLE_BUILD_NUM="actually-actions-${RUN_ID}"
          conda-forge-tick --run -1

          popd
        env:
          PASSWORD: ${{ secrets.AUTOTICK_BOT_TOKEN }}
          RUN_ID: ${{ github.run_id }}

      - name: bump on fail
        shell: bash -l {0}
        if: github.ref == 'refs/heads/master' && failure() && ! env.CI_SKIP && ! steps.turnstyle.outputs.force_continued
        run: |
          export ACTION_URL="https://github.com/regro/autotick-bot/actions/runs/${RUN_ID}"
          python bump_bot_team.py
        env:
          PASSWORD: ${{ secrets.AUTOTICK_BOT_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          ACTION_NAME: ${{ github.workflow }}
